export const statuses = [
  { label: 'Đang xử lý', value: 'Processing' },
  { label: 'Chờ xác nhận', value: 'Pending' },
  { label: 'Đã xác nhận', value: 'Confirmed' },
  { label: 'Đang chờ bên vận chuyển', value: 'Pending-Ship' },
  { label: 'Đang vận chuyển', value: 'Delivering' },
  { label: 'Giao hàng thành công', value: 'Delivered' },
  { label: 'Đơn hàng hoàn thành', value: 'Completed' },
  { label: 'Tiến hành hoàn trả', value: 'Returning' },
  { label: 'Từ chối hoàn trả', value: 'Rejected' },
  { label: 'Hoàn trả đơn hàng', value: 'Returned' },
  { label: 'Tiến hành hoàn tiền', value: 'Refunding' },
  { label: 'Hoàn tiền đơn hàng', value: 'Refunded' },
  { label: 'Đã hủy đơn hàng', value: 'Cancelled' },
];
export const statusColors = {
  Processing: 'blue',
  Pending: 'orange',
  Confirmed: 'green',
  'Pending-Ship': 'cyan',
  Delivering: 'purple',
  Delivered: 'green',
  Completed: 'gold',
  Returning: 'orange',
  Rejected: 'red',
  Returned: 'red',
  Refunding: 'orange',
  Refunded: 'red',
  Cancelled: 'gray',
};
